### ISSUE TITLE
设置到期礼物自动送出后出现如下错误

### ISSUE THREAD

**Issue by baizimujun** [KurenaiRyu/bilibili-helper-runer#1]
-----B站直播送出即将过期的礼物开始-----

💔赠送礼物异常 :

java.lang.NullPointerException: null at top.misec.task.GiveGift.getuidAndRid(GiveGift.java:180) ~[BILIBILI-HELPER.jar:?] at top.misec.task.GiveGift.run(GiveGift.java:54) [BILIBILI-HELPER.jar:?] at top.misec.task.DailyTask.doDailyTask(DailyTask.java:42) [BILIBILI-HELPER.jar:?] at top.misec.BiliMain.main(BiliMain.java:36) [BILIBILI-HELPER.jar:?] -----B站直播送出即将过期的礼物结束-----

**Comment by KurenaiRyu** [comment]
抱歉，我这个项目只是做了拉去最新发版的程序并运行，程序那边我其实没怎么参与维护，建议反馈给原项目（[BILIBILI-HELPER](https://github.com/JunzhouLiu/BILIBILI-HELPER)）

我先关了这个讨论，如果还有什么问题可以继续打开
